apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    spec:
      containers:
        - name: django-container
          resources:
            limits:
              memory: 8000Mi
            requests:
              memory: 6000Mi
          envFrom:
            - configMapRef:
                name: app-config-fallback
            - configMapRef:
                name: db-config-fallback
            - secretRef:
                name: db-secret-fallback
