language: python

python: 
   - "3.6.4"

services: 
  - mysql

env: 
  - DJANGO=2.1.7 DB=mysql DJANGO_ENVIRONMENT=travis

install: 
  - pip install -r requirements.txt

before_script: 
  - mysql -e 'create database tark_django_manager;' -u root
  - mysql -e 'create database tark;' -u root
  - cp tark/tark/settings/secrets_template.py tark/tark/settings/secrets.py
  - mkdir logs
  - touch logs/tark.log

script: 
  - coverage run --source=. tark/manage.py test assembly.tests exon.tests tark.tests tark_web.tests tark_drf.tests transcript.tests release.tests --settings=tark.settings.test

# send coverage report to coveralls
after_success:
  coveralls
