# App variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DJANGO_ALLOWED_HOSTS: "hh-rke-wp-webadmin-31-worker-1.caas.ebi.ac.uk hh-rke-wp-webadmin-31-worker-2.caas.ebi.ac.uk hh-rke-wp-webadmin-31-worker-3.caas.ebi.ac.uk tark.ensembl.org"
  WORKERS: "7"