apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    spec:
      containers:        
        - name: django-container
          resources:
           limits:
             memory: 16000Mi
           requests:
             memory: 12000Mi
          envFrom:
          - configMapRef:
              name: app-config-production
          - configMapRef:
              name: db-config-production
          - secretRef:
              name: db-secret-production