apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      imagePullSecrets:
      - name: backend-registry-secret
      containers:
      - name: django-container
        image: <DOCKER_IMAGE>
        imagePullPolicy: Always
        command: ["gunicorn"]
        args: [
            "--bind",
            "0.0.0.0:8000",
            "--timeout",
            "120",
            "--workers",
            "$(WORKERS)",
            "tark.wsgi:application"
          ]
        ports:
        - containerPort: 8000