apiVersion: v1
kind: Service
metadata:
  name: app-nodeport-service
  # namespace: plantgwas-staging
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32450
  selector:
    app: django