apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app/django-deployment.yaml
  - app/django-service.yaml
  - app/nodeport-service.yaml

  - config/app-config.yaml
  - config/db-config.yaml

  - mysql/mysql-endpoint.yaml
  - mysql/mysql-service.yaml

  - ingress/ingress-resource.yaml